# Generated by Django 3.2.9 on 2022-01-23 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bodey',
            new_name='body',
        ),
    ]
